# Generated by Django 3.1 on 2020-09-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField()),
                ('event', models.PositiveSmallIntegerField()),
                ('prob_1', models.FloatField()),
                ('prob_2', models.FloatField()),
                ('prob_3', models.FloatField()),
                ('prob_4', models.FloatField()),
                ('prob_5', models.FloatField()),
                ('prob_6', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.PositiveSmallIntegerField()),
                ('stime', models.DateTimeField()),
                ('hello_num', models.PositiveSmallIntegerField()),
                ('lsr_num', models.PositiveSmallIntegerField()),
                ('lsu_num', models.PositiveSmallIntegerField()),
                ('lsa_num', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.PositiveSmallIntegerField()),
                ('port', models.PositiveSmallIntegerField()),
                ('portip', models.GenericIPAddressField()),
                ('neibrid', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
